# Welcome to Jekyll!

# Site settings
title: On and off programming
# email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  This is my blog about programming.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://findanddelete.github.io" # the base hostname & protocol for your site
# twitter_username:
github_username:  draperjames
# Build settings
markdown: kramdown

post:
  template: _post.txt
  extension: markdown

page:
  template: _page.txt
  extension: md
